/*
 * ItemBrowser.java
 *
 * Created on January 25, 2005, 12:32 PM
 */

package theatre;

import javax.swing.JTextArea;
import javax.swing.JTextField;
import Data_Storage.*;

/**
 *
 * @author  Administrator
 */
public class ItemBrowser extends Window {
    
    /** Creates new form ItemBrowser */
    public ItemBrowser() 
    {
    	initComponents();
        this.setTitle("Item Browser");
        this.setBounds(BasicWindow.iScreenWidth-(BasicWindow.iScreenWidth/5), 0, BasicWindow.iScreenWidth/5-5, BasicWindow.iScreenHeight/2-20);
        this.setVisible(true);
    }
    public static void displayInfo(Object o)
    {
    	if (o instanceof bar)
    	{
    		bar b = (bar)o;
    		String s = "Bar ID: "+b.getID()+"\n";
    		s += "Num Nodes: "+b.num_nodes + "\n";
    		s += "x: "+b.worldx+"\n";
    		s += "y: "+b.worldy+"\n";
    		s += "number of dimmers: " + b.getNum_dimmers()+"\n";
    		jText.setText(s);
    	}
    	//jTable1.add
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        //jTable1 = new javax.swing.JTable();
    	jText = new JTextArea();

        getContentPane().setLayout(null);

        /*jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));*/
        getContentPane().add(jText);
        jText.setBounds(0, 0, 230, 210);

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    //public static javax.swing.JTable jTable1;
    public static JTextArea jText;
    // End of variables declaration//GEN-END:variables
    
}
